txt = "The best things in life are free!"
print(len(txt))
print(txt[0])
print(txt.split())
print(txt.split("i"))
print(txt[29])
print(txt.count('f', 20, 30))
print(txt.join("!"))
print(txt.isdigit())
print(txt.find('a', 20, 28))
print(txt.lower())
print(txt.upper())
print(txt.index('l', 12, 29))
print(txt.replace('life', 'newlife'))
print(txt.isalpha())
print(txt.swapcase())
print(txt.istitle())
